version: "3.8"

services:
  nginx:
    image: nginx:1.25.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    entrypoint: sh -c "/usr/sbin/cron -f & php-fpm"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mockcase-entry-database1.cf84csggk1dn.ap-southeast-2.rds.amazonaws.com
      - PMA_USER=admin
      - PMA_PASSWORD=Entry_Coach1
    ports:
      - 8080:80
